openapi: 3.0.0

paths:
  /user/{userId}:
    get:
      summary: This endpoint returns an user given an user id
      parameters:
        - name: userId
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:getUser/invocations"
        httpMethod: "POST"
        
    put:
      summary: This endpoint saves an user in the database 
      parameters:
        - name: userId
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:putUser/invocations"
        httpMethod: "POST"